// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noofbavcmxkoqwazqtxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vb2ZiYXZjbXhrb3F3YXpxdHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDA3NDgsImV4cCI6MjA1NzIxNjc0OH0.09pW5V0LPiXuf3RNU3gxckgfgz22CosD-FSJy35Wa_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);